language: node_js

matrix:
  include:
  - os: linux
    node_js: v10.0.0

  - os: osx
    osx_image: xcode10.2
    node_js: v10.0.0

  - os: windows
    node_js: v10.0.0
    env:
    - ARCHIVE_FILES_DISABLE_MTIME_TESTING=1

  - os: linux
    node_js: v10.16.3

  - os: osx
    osx_image: xcode10.2
    node_js: v10.16.3

  - os: windows
    node_js: v10.16.3
    env:
    - ARCHIVE_FILES_DISABLE_MTIME_TESTING=1

  - os: linux
    node_js: v12.9.1

  - os: osx
    osx_image: xcode10.2
    node_js: v12.9.1

  - os: windows
    node_js: v12.9.1
    env:
    - ARCHIVE_FILES_DISABLE_MTIME_TESTING=1

script:
- npm run clean
- npm run lint
- npm run build
- npm run test
