language: node_js

matrix:
  include:
  - os: linux
    node_js: v10.0.0
    env:
    - NO_LINT=1

  - os: osx
    osx_image: xcode12 # 10.15
    node_js: v10.0.0
    env:
    - NO_LINT=1

  - os: windows
    node_js: v10.0.0
    env:
    - NO_LINT=1
    - ARCHIVE_FILES_DISABLE_MTIME_TESTING=1

  - os: linux
    node_js: v14.11.0

  - os: osx
    osx_image: xcode12 # 10.15
    node_js: v14.11.0

  - os: windows
    node_js: v14.11.0
    env:
    - ARCHIVE_FILES_DISABLE_MTIME_TESTING=1

script:
- npm run clean
- if [ "$NO_LINT" != "1" ]; then npm run lint; fi
- npm run build
- npm run test
